config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'status' => 'status#index'

  resources :muscular_groups

  root to: 'muscular_groups#index'
end

app/models/exercise.rb
class Exercise
	include Mongoid::Document
	include Mongoid::Timestamps

	field :name, type: String

	embedded_in :muscular_group
	embedded_in :exercise_training
end

app/models/exercise_training.rb
class ExerciseTraining
	include Mongoid::Document
	include Mongoid::Timestamps

	field :series, type: Integer
	field :repetition, type: Integer
	field :weight, type: Integer
	field :order, type: Integer

	embeds_one :exercise
	embedded_in :training
end

app/models/muscular_group.rb
class MuscularGroup
	include Mongoid::Document
	include Mongoid::Timestamps

	field :name, type: String

	embeds_many :exercises
end

app/models/training.rb
class Training
	include Mongoid::Document
	include Mongoid::Timestamps

	field :name, type: Symbol

	embeds_many :exercises_training, class_name: 'ExerciseTraining'
end

app/models/training_plan.rb
class TrainingPlan
	include Mongoid::Document
	include Mongoid::Timestamps

	field :status, type: Symbol
	field :start_date, type: DateTime
	field :duration, type: Integer

	embeds_many :trainings, class_name: 'Training'
	embedded_in :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :name, type: String

  embeds_many :training_plans, class_name: 'TrainingPlan'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/muscular_groups_controller.rb
class MuscularGroupsController < ApplicationController
  before_action :set_muscular_group, only: [:show, :edit, :update, :destroy]

  # GET /muscular_groups
  # GET /muscular_groups.json
  def index
    @muscular_groups = MuscularGroup.all
  end

  # GET /muscular_groups/1
  # GET /muscular_groups/1.json
  def show
  end

  # GET /muscular_groups/new
  def new
    @muscular_group = MuscularGroup.new
  end

  # GET /muscular_groups/1/edit
  def edit
  end

  # POST /muscular_groups
  # POST /muscular_groups.json
  def create
    @muscular_group = MuscularGroup.new(muscular_group_params)

    respond_to do |format|
      if @muscular_group.save
        format.html { redirect_to @muscular_group, notice: 'Muscular group was successfully created.' }
        format.json { render :show, status: :created, location: @muscular_group }
      else
        format.html { render :new }
        format.json { render json: @muscular_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /muscular_groups/1
  # PATCH/PUT /muscular_groups/1.json
  def update
    respond_to do |format|
      if @muscular_group.update(muscular_group_params)
        format.html { redirect_to @muscular_group, notice: 'Muscular group was successfully updated.' }
        format.json { render :show, status: :ok, location: @muscular_group }
      else
        format.html { render :edit }
        format.json { render json: @muscular_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /muscular_groups/1
  # DELETE /muscular_groups/1.json
  def destroy
    @muscular_group.destroy
    respond_to do |format|
      format.html { redirect_to muscular_groups_url, notice: 'Muscular group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_muscular_group
      @muscular_group = MuscularGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def muscular_group_params
      params.require(:muscular_group).permit(:name)
    end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
	def index
		@message = 'Up and running'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/muscular_groups_helper.rb
module MuscularGroupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gym</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/muscular_groups/_form.html.erb
<%= form_with(model: muscular_group, local: true) do |form| %>
  <% if muscular_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(muscular_group.errors.count, "error") %> prohibited this muscular_group from being saved:</h2>

      <ul>
      <% muscular_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :muscular_group_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/muscular_groups/edit.html.erb
<h1>Editing Muscular Group</h1>

<%= render 'form', muscular_group: @muscular_group %>

<%= link_to 'Show', @muscular_group %> |
<%= link_to 'Back', muscular_groups_path %>

app/views/muscular_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Muscular Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @muscular_groups.each do |muscular_group| %>
      <tr>
        <td><%= muscular_group.name %></td>
        <td><%= link_to 'Show', muscular_group %></td>
        <td><%= link_to 'Edit', edit_muscular_group_path(muscular_group) %></td>
        <td><%= link_to 'Destroy', muscular_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Muscular Group', new_muscular_group_path %>

app/views/muscular_groups/new.html.erb
<h1>New Muscular Group</h1>

<%= render 'form', muscular_group: @muscular_group %>

<%= link_to 'Back', muscular_groups_path %>

app/views/muscular_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @muscular_group.name %>
</p>

<%= link_to 'Edit', edit_muscular_group_path(@muscular_group) %> |
<%= link_to 'Back', muscular_groups_path %>